Models/Fornecedor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace CrudFornecedor.Models
{
    public class Fornecedor
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome do fornecedor"), Column("Nome", TypeName = "nvarchar(100)")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Digite o CNPJ do fornecedor"), Column("CNPJ", TypeName = "nvarchar(14)")]
        public string CNPJ { get; set; }
        [Required(ErrorMessage = "Selecione a especialidade do fornecedor")]
        public string Especialidade { get; set; }  
    }
}

Controllers/FornecedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CrudFornecedor.Models;
using CrudFornecedor.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace CrudFornecedor.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly IFornecedorRepositorio _fornecedorRepositorio;

        public FornecedorController(IFornecedorRepositorio fornecedorRepositorio)
        {
            _fornecedorRepositorio = fornecedorRepositorio;
        }

        public IActionResult Index()
        {
            var fornecedores = _fornecedorRepositorio.BuscarTodos();
            return View(fornecedores);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Fornecedor fornecedor)
        {
            try
            {
                if(ModelState.IsValid)
            {
                _fornecedorRepositorio.Adicionar(fornecedor);
                TempData["MensagemSucesso"] = "Salvo com sucesso!";
                return RedirectToAction("Index");
            }
            
            return View(fornecedor);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Algo deu errado!, detalhes do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Editar(int id)
        {
            Fornecedor fornecedor =  _fornecedorRepositorio.ListarPorId(id);
            return View(fornecedor);
        }
        [HttpPost]
        public IActionResult Alterar(Fornecedor fornecedor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _fornecedorRepositorio.Atualizar(fornecedor);
                    TempData["MensagemSucesso"] = "Alterado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View("Editar", fornecedor);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Algo deu errado!, detalhes do erro:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
        
        public IActionResult ApagarConfirmacao(int id)
        {
            Fornecedor fornecedor =  _fornecedorRepositorio.ListarPorId(id);
            return View(fornecedor);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _fornecedorRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Excluído com sucesso!"; 
                }
                else
                {
                    TempData["MensagemErro"] = $"Algo deu errado!";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Algo deu errado! mais detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CrudFornecedor.Models;

namespace CrudFornecedor.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Views/Fornecedor/ApagarConfirmacao.cshtml
@model Fornecedor
@{
    ViewData["Title"] = "Confirmação excluir o fornecedor";
}

<div class="text-center">
    <h3>Realmente deseja excluir o fornecedor (@Model.Nome)?</h3>
</div>

<a id="rebelde" class="btn btn-danger" role="button" asp-controller="Fornecedor" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>
<a id="rebelde" class="btn btn-primary" role="button" asp-controller="Fornecedor" asp-action="Index">Cancelar exclusão</a>

Views/Fornecedor/Criar.cshtml
@model Fornecedor
@{
    ViewData["Title"] = "Cadastrar fornecedor";
}

<form asp-controller="Fornecedor" asp-action="Criar" method="post">
    <div class="text-center">
        <h1>Adicionar fornecedor</h1>
    </div>
    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Nome do fornecedor" maxlength="100">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <div class="mb-3">
        <label for="cnpj" class="form-label">CNPJ</label>
        <input type="text" asp-for="CNPJ" class="form-control" placeholder="Apenas Números" maxlength="14" pattern="[0-9]{14,14}">
        @Html.ValidationMessageFor(x => x.CNPJ)
    </div>

    <div class="form-floating">
        <select class="form-select" asp-for="Especialidade">
            <option selected value="">Selecione uma opção</option>
            <option value="Comércio">Comércio</option>
            <option value="Serviço">Serviço</option>
            <option value="Indústria">Indústria</option>
        </select>
        <label for="floatingSelect">Especialidade</label>
        @Html.ValidationMessageFor(x => x.Especialidade)
    </div>
    <br />
    <button id="rebelde" class="btn btn-primary" type="submit">Adicionar</button>
    <a class=" d-grid gap-2 btn btn-secondary" asp-controller="Fornecedor" asp-action="Index" role="button">Voltar</a>
</form>

Views/Fornecedor/Editar.cshtml
@model Fornecedor
@{
    ViewData["Title"] = "Cadastrar fornecedor";
}


<form asp-controller="Fornecedor" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id" />
    
    <div class="text-center">
        <h1>Cadastrar fornecedor</h1>
    </div>
    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Nome do fornecedor" maxlength="100">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <div class="mb-3">
        <label for="cnpj" class="form-label">CNPJ</label>
        <input type="text" asp-for="CNPJ" class="form-control" placeholder="Apenas Números" maxlength="14" pattern="[0-9]{14,14}">
        @Html.ValidationMessageFor(x => x.CNPJ)
    </div>

    <div class="form-floating">
        <select class="form-select" asp-for="Especialidade">
            <option value="Comércio">Comércio</option>
            <option value="Serviço">Serviço</option>
            <option value="Indústria">Indústria</option>
        </select>
        <label for="floatingSelect">Especialidade</label>
        @Html.ValidationMessageFor(x => x.Especialidade)
    </div>
    <br />
    <button id="rebelde" class="btn btn-primary" type="submit">Alterar</button>
    <a class=" d-grid gap-2 btn btn-secondary" asp-controller="Fornecedor" asp-action="Index" role="button">Voltar</a>
</form>

Views/Fornecedor/Index.cshtml
@model List<Fornecedor>
@{
    ViewData["Title"] = "Listagem de fornecedores";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Fornecedor" asp-action="Criar">Adicionar fornecedor</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div> 
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }
    <br />
    <h1>Fornecedores</h1>
    <br />

    <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">CNPJ</th>
            <th scope="col">Especialidade</th>
            <th scope="col"></th>
        </tr>
    </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td>@item.Nome</td>
                        <td>@item.CNPJ</td>
                        <td>@item.Especialidade</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-secondary" asp-route-id="@item.Id" asp-controller="Fornecedor" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@item.Id" asp-controller="Fornecedor" asp-action="ApagarConfirmacao">Excluir</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Sistema de controle de fornecedores</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de fornecedores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudFornecedor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de fornecedores</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Controle de fornecedores
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>